create view sys.identity_columns as
-- missing source code
go

grant select on sys.identity_columns to [public]
go

INSERT INTO sys.identity_columns (object_id, name, column_id, system_type_id, user_type_id, max_length, precision, scale, collation_name, is_nullable, is_ansi_padded, is_rowguidcol, is_identity, is_filestream, is_replicated, is_non_sql_subscribed, is_merge_published, is_dts_replicated, is_xml_document, xml_collection_id, default_object_id, rule_object_id, seed_value, increment_value, last_value, is_not_for_replication, is_computed, is_sparse, is_column_set, generated_always_type, generated_always_type_desc, encryption_type, encryption_type_desc, encryption_algorithm_name, column_encryption_key_id, column_encryption_key_database_name, is_hidden, is_masked, graph_type, graph_type_desc) VALUES (133575514, N'instance_id', 1, 56, 56, 4, 10, 0, null, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, N'1', N'1', null, 0, 0, 0, 0, 0, N'NOT_APPLICABLE', null, null, null, null, null, 0, 0, null, null);
INSERT INTO sys.identity_columns (object_id, name, column_id, system_type_id, user_type_id, max_length, precision, scale, collation_name, is_nullable, is_ansi_padded, is_rowguidcol, is_identity, is_filestream, is_replicated, is_non_sql_subscribed, is_merge_published, is_dts_replicated, is_xml_document, xml_collection_id, default_object_id, rule_object_id, seed_value, increment_value, last_value, is_not_for_replication, is_computed, is_sparse, is_column_set, generated_always_type, generated_always_type_desc, encryption_type, encryption_type_desc, encryption_algorithm_name, column_encryption_key_id, column_encryption_key_database_name, is_hidden, is_masked, graph_type, graph_type_desc) VALUES (149575571, N'log_id', 1, 56, 56, 4, 10, 0, null, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, N'1', N'1', null, 0, 0, 0, 0, 0, N'NOT_APPLICABLE', null, null, null, null, null, 0, 0, null, null);
INSERT INTO sys.identity_columns (object_id, name, column_id, system_type_id, user_type_id, max_length, precision, scale, collation_name, is_nullable, is_ansi_padded, is_rowguidcol, is_identity, is_filestream, is_replicated, is_non_sql_subscribed, is_merge_published, is_dts_replicated, is_xml_document, xml_collection_id, default_object_id, rule_object_id, seed_value, increment_value, last_value, is_not_for_replication, is_computed, is_sparse, is_column_set, generated_always_type, generated_always_type_desc, encryption_type, encryption_type_desc, encryption_algorithm_name, column_encryption_key_id, column_encryption_key_database_name, is_hidden, is_masked, graph_type, graph_type_desc) VALUES (1993058136, N'queuing_order', 3, 127, 127, 8, 19, 0, null, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, N'0', N'1', null, 0, 0, 0, 0, 0, N'NOT_APPLICABLE', null, null, null, null, null, 0, 0, null, null);
INSERT INTO sys.identity_columns (object_id, name, column_id, system_type_id, user_type_id, max_length, precision, scale, collation_name, is_nullable, is_ansi_padded, is_rowguidcol, is_identity, is_filestream, is_replicated, is_non_sql_subscribed, is_merge_published, is_dts_replicated, is_xml_document, xml_collection_id, default_object_id, rule_object_id, seed_value, increment_value, last_value, is_not_for_replication, is_computed, is_sparse, is_column_set, generated_always_type, generated_always_type_desc, encryption_type, encryption_type_desc, encryption_algorithm_name, column_encryption_key_id, column_encryption_key_database_name, is_hidden, is_masked, graph_type, graph_type_desc) VALUES (2025058250, N'queuing_order', 3, 127, 127, 8, 19, 0, null, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, N'0', N'1', null, 0, 0, 0, 0, 0, N'NOT_APPLICABLE', null, null, null, null, null, 0, 0, null, null);
INSERT INTO sys.identity_columns (object_id, name, column_id, system_type_id, user_type_id, max_length, precision, scale, collation_name, is_nullable, is_ansi_padded, is_rowguidcol, is_identity, is_filestream, is_replicated, is_non_sql_subscribed, is_merge_published, is_dts_replicated, is_xml_document, xml_collection_id, default_object_id, rule_object_id, seed_value, increment_value, last_value, is_not_for_replication, is_computed, is_sparse, is_column_set, generated_always_type, generated_always_type_desc, encryption_type, encryption_type_desc, encryption_algorithm_name, column_encryption_key_id, column_encryption_key_database_name, is_hidden, is_masked, graph_type, graph_type_desc) VALUES (2057058364, N'queuing_order', 3, 127, 127, 8, 19, 0, null, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, N'0', N'1', null, 0, 0, 0, 0, 0, N'NOT_APPLICABLE', null, null, null, null, null, 0, 0, null, null);
