create view sys.dm_db_script_level as
-- missing source code
go

INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 0, N'procsyst.sql', 1, 2, 2, 2, 0, 2);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 1, N'u_tables.sql', 1, 569, 2, 2, 0, 569);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 2, N'ProvisionAgentIdentity.sql', 1, 251660240, 2, 2, 0, 251660240);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 3, N'no_op.sql', 1, 251660240, 2, 2, 0, 251660240);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 4, N'no_op.sql', 1, 2, 2, 2, 2, 2);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 5, N'sqlagent90_sysdbupg.sql', 1, 2, 2, 2, 0, 2);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 6, N'sqlagent100_msdb_upgrade.sql', 1, 549, 2, 2, 2, 549);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 7, N'no_op.sql', 1, 251660240, 2, 2, 0, 251660240);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 8, N'repl_upgrade.sql', 1, 251660240, 2, 2, 0, 251660240);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 9, N'provisionsystemaccounts.sql', 1, 501, 2, 2, 0, 501);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 10, N'provisionexpress.sql', 1, 2, 2, 2, 0, 2);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 11, N'upgrade_ucp_cmdw_discovery.sql', 1, 251660240, 2, 2, 0, 251660240);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 12, N'upgrade_ucp_cmdw.sql', 1, 2, 2, 2, 2, 2);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 13, N'msdb110_upgrade.sql', 1, 251660240, 500, 500, 500, 251660240);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 14, N'upgrade_ucp_cmdw_discovery.sql', 1, 251660240, 500, 500, 0, 251660240);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 15, N'upgrade_ucp_cmdw.sql', 1, 500, 500, 500, 500, 500);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 16, N'ssis_discovery', 1, 251660240, 500, 500, 0, 251660240);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 17, N'ISServer_upgrade.sql', 1, 500, 500, 500, 500, 500);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 18, N'SSIS_hotfix_install.sql', 1, 251660240, 549, 549, 549, 251660240);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 19, N'shutdown_xevents_add.sql', 1, 702, 702, 702, 0, 702);
INSERT INTO sys.dm_db_script_level (database_id, script_id, script_name, version, script_level, downgrade_start_level, downgrade_target_level, upgrade_start_level, upgrade_target_level) VALUES (1, 20, N'provision_ceipsvc_account.sql', 1, 251660240, 702, 702, 0, 251660240);
