create view INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS as
-- missing source code
go

INSERT INTO INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS (CONSTRAINT_CATALOG, CONSTRAINT_SCHEMA, CONSTRAINT_NAME, UNIQUE_CONSTRAINT_CATALOG, UNIQUE_CONSTRAINT_SCHEMA, UNIQUE_CONSTRAINT_NAME, MATCH_OPTION, UPDATE_RULE, DELETE_RULE) VALUES (N'db_rc', N'dbo', N't_rented_t_car_id_fk', N'db_rc', N'dbo', N'PK__t_car__3213E83F32068265', N'SIMPLE', N'NO ACTION', N'NO ACTION');
INSERT INTO INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS (CONSTRAINT_CATALOG, CONSTRAINT_SCHEMA, CONSTRAINT_NAME, UNIQUE_CONSTRAINT_CATALOG, UNIQUE_CONSTRAINT_SCHEMA, UNIQUE_CONSTRAINT_NAME, MATCH_OPTION, UPDATE_RULE, DELETE_RULE) VALUES (N'db_rc', N'dbo', N't_rented_t_user_id_fk', N'db_rc', N'dbo', N'PK__t_usr__3213E83F67A1B7B9', N'SIMPLE', N'NO ACTION', N'NO ACTION');
