create view INFORMATION_SCHEMA.TABLES as
-- missing source code
go

INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES (N'db_rc', N'dbo', N't_usr', N'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES (N'db_rc', N'dbo', N't_car', N'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES (N'db_rc', N'dbo', N't_rented', N'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES (N'db_rc', N'dbo', N't_maintain', N'BASE TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLES (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE) VALUES (N'db_rc', N'dbo', N't_admin', N'BASE TABLE');
