create view sys.time_zone_info as
-- missing source code
go

grant select on sys.time_zone_info to [public]
go

INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Dateline Standard Time', N'-12:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'UTC-11', N'-11:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Hawaiian Standard Time', N'-10:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Aleutian Standard Time', N'-10:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Marquesas Standard Time', N'-09:30', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'UTC-09', N'-09:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Alaskan Standard Time', N'-09:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Pacific Standard Time (Mexico)', N'-08:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'UTC-08', N'-08:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Pacific Standard Time', N'-08:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'US Mountain Standard Time', N'-07:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Mountain Standard Time (Mexico)', N'-07:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Mountain Standard Time', N'-07:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Yukon Standard Time', N'-07:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Central America Standard Time', N'-06:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Central Standard Time', N'-06:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Easter Island Standard Time', N'-05:00', 1);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Central Standard Time (Mexico)', N'-06:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Canada Central Standard Time', N'-06:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Eastern Standard Time', N'-05:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Eastern Standard Time (Mexico)', N'-05:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'US Eastern Standard Time', N'-05:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Cuba Standard Time', N'-05:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'SA Pacific Standard Time', N'-05:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Haiti Standard Time', N'-05:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Turks And Caicos Standard Time', N'-05:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'SA Western Standard Time', N'-04:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Paraguay Standard Time', N'-03:00', 1);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Venezuela Standard Time', N'-04:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Pacific SA Standard Time', N'-03:00', 1);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Atlantic Standard Time', N'-04:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Central Brazilian Standard Time', N'-04:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Newfoundland Standard Time', N'-03:30', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'SA Eastern Standard Time', N'-03:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Saint Pierre Standard Time', N'-03:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'E. South America Standard Time', N'-03:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Argentina Standard Time', N'-03:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Greenland Standard Time', N'-03:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Bahia Standard Time', N'-03:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Montevideo Standard Time', N'-03:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Magallanes Standard Time', N'-03:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Tocantins Standard Time', N'-03:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Mid-Atlantic Standard Time', N'-02:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'UTC-02', N'-02:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Azores Standard Time', N'-01:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Cape Verde Standard Time', N'-01:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'UTC', N'+00:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Sao Tome Standard Time', N'+00:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Greenwich Standard Time', N'+00:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'GMT Standard Time', N'+00:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Morocco Standard Time', N'+01:00', 1);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'W. Central Africa Standard Time', N'+01:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Romance Standard Time', N'+01:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Central European Standard Time', N'+01:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Central Europe Standard Time', N'+01:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'W. Europe Standard Time', N'+01:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'West Bank Standard Time', N'+02:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Kaliningrad Standard Time', N'+02:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'South Africa Standard Time', N'+02:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Sudan Standard Time', N'+02:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'E. Europe Standard Time', N'+02:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Syria Standard Time', N'+02:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Jordan Standard Time', N'+02:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Egypt Standard Time', N'+02:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'South Sudan Standard Time', N'+02:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Namibia Standard Time', N'+02:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Libya Standard Time', N'+02:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Israel Standard Time', N'+02:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Middle East Standard Time', N'+02:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'FLE Standard Time', N'+02:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'GTB Standard Time', N'+02:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Turkey Standard Time', N'+03:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Volgograd Standard Time', N'+03:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'E. Africa Standard Time', N'+03:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Arabic Standard Time', N'+03:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Belarus Standard Time', N'+03:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Arab Standard Time', N'+03:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Russian Standard Time', N'+03:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Iran Standard Time', N'+03:30', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Russia Time Zone 3', N'+04:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Caucasus Standard Time', N'+04:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Azerbaijan Standard Time', N'+04:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Georgian Standard Time', N'+04:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Saratov Standard Time', N'+04:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Mauritius Standard Time', N'+04:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Arabian Standard Time', N'+04:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Astrakhan Standard Time', N'+04:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Afghanistan Standard Time', N'+04:30', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Pakistan Standard Time', N'+05:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Qyzylorda Standard Time', N'+05:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Ekaterinburg Standard Time', N'+05:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'West Asia Standard Time', N'+05:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Sri Lanka Standard Time', N'+05:30', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'India Standard Time', N'+05:30', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Nepal Standard Time', N'+05:45', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Bangladesh Standard Time', N'+06:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Omsk Standard Time', N'+06:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Central Asia Standard Time', N'+06:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Myanmar Standard Time', N'+06:30', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'North Asia Standard Time', N'+07:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Altai Standard Time', N'+07:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Tomsk Standard Time', N'+07:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'N. Central Asia Standard Time', N'+07:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'SE Asia Standard Time', N'+07:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'W. Mongolia Standard Time', N'+07:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Ulaanbaatar Standard Time', N'+08:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'North Asia East Standard Time', N'+08:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'China Standard Time', N'+08:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Taipei Standard Time', N'+08:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Singapore Standard Time', N'+08:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'W. Australia Standard Time', N'+08:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Aus Central W. Standard Time', N'+08:45', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Tokyo Standard Time', N'+09:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'North Korea Standard Time', N'+09:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Transbaikal Standard Time', N'+09:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Yakutsk Standard Time', N'+09:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Korea Standard Time', N'+09:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'AUS Central Standard Time', N'+09:30', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Cen. Australia Standard Time', N'+10:30', 1);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'West Pacific Standard Time', N'+10:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'AUS Eastern Standard Time', N'+11:00', 1);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'E. Australia Standard Time', N'+10:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Vladivostok Standard Time', N'+10:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Tasmania Standard Time', N'+11:00', 1);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Lord Howe Standard Time', N'+11:00', 1);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Russia Time Zone 10', N'+11:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Bougainville Standard Time', N'+11:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Central Pacific Standard Time', N'+11:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Sakhalin Standard Time', N'+11:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Norfolk Standard Time', N'+12:00', 1);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Magadan Standard Time', N'+11:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'UTC+12', N'+12:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'New Zealand Standard Time', N'+13:00', 1);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Kamchatka Standard Time', N'+12:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Fiji Standard Time', N'+12:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Russia Time Zone 11', N'+12:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Chatham Islands Standard Time', N'+13:45', 1);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Tonga Standard Time', N'+13:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'UTC+13', N'+13:00', 0);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Samoa Standard Time', N'+14:00', 1);
INSERT INTO sys.time_zone_info (name, current_utc_offset, is_currently_dst) VALUES (N'Line Islands Standard Time', N'+14:00', 0);
