create view sys.database_mirroring as
-- missing source code
go

INSERT INTO sys.database_mirroring (database_id, mirroring_guid, mirroring_state, mirroring_state_desc, mirroring_role, mirroring_role_desc, mirroring_role_sequence, mirroring_safety_level, mirroring_safety_level_desc, mirroring_safety_sequence, mirroring_partner_name, mirroring_partner_instance, mirroring_witness_name, mirroring_witness_state, mirroring_witness_state_desc, mirroring_failover_lsn, mirroring_connection_timeout, mirroring_redo_queue, mirroring_redo_queue_type, mirroring_end_of_log_lsn, mirroring_replication_lsn) VALUES (1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO sys.database_mirroring (database_id, mirroring_guid, mirroring_state, mirroring_state_desc, mirroring_role, mirroring_role_desc, mirroring_role_sequence, mirroring_safety_level, mirroring_safety_level_desc, mirroring_safety_sequence, mirroring_partner_name, mirroring_partner_instance, mirroring_witness_name, mirroring_witness_state, mirroring_witness_state_desc, mirroring_failover_lsn, mirroring_connection_timeout, mirroring_redo_queue, mirroring_redo_queue_type, mirroring_end_of_log_lsn, mirroring_replication_lsn) VALUES (2, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO sys.database_mirroring (database_id, mirroring_guid, mirroring_state, mirroring_state_desc, mirroring_role, mirroring_role_desc, mirroring_role_sequence, mirroring_safety_level, mirroring_safety_level_desc, mirroring_safety_sequence, mirroring_partner_name, mirroring_partner_instance, mirroring_witness_name, mirroring_witness_state, mirroring_witness_state_desc, mirroring_failover_lsn, mirroring_connection_timeout, mirroring_redo_queue, mirroring_redo_queue_type, mirroring_end_of_log_lsn, mirroring_replication_lsn) VALUES (3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO sys.database_mirroring (database_id, mirroring_guid, mirroring_state, mirroring_state_desc, mirroring_role, mirroring_role_desc, mirroring_role_sequence, mirroring_safety_level, mirroring_safety_level_desc, mirroring_safety_sequence, mirroring_partner_name, mirroring_partner_instance, mirroring_witness_name, mirroring_witness_state, mirroring_witness_state_desc, mirroring_failover_lsn, mirroring_connection_timeout, mirroring_redo_queue, mirroring_redo_queue_type, mirroring_end_of_log_lsn, mirroring_replication_lsn) VALUES (4, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO sys.database_mirroring (database_id, mirroring_guid, mirroring_state, mirroring_state_desc, mirroring_role, mirroring_role_desc, mirroring_role_sequence, mirroring_safety_level, mirroring_safety_level_desc, mirroring_safety_sequence, mirroring_partner_name, mirroring_partner_instance, mirroring_witness_name, mirroring_witness_state, mirroring_witness_state_desc, mirroring_failover_lsn, mirroring_connection_timeout, mirroring_redo_queue, mirroring_redo_queue_type, mirroring_end_of_log_lsn, mirroring_replication_lsn) VALUES (5, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
