create view sys.tables as
-- missing source code
go

grant select on sys.tables to [public]
go

INSERT INTO sys.tables (name, object_id, principal_id, schema_id, parent_object_id, type, type_desc, create_date, modify_date, is_ms_shipped, is_published, is_schema_published, lob_data_space_id, filestream_data_space_id, max_column_id_used, lock_on_bulk_load, uses_ansi_nulls, is_replicated, has_replication_filter, is_merge_published, is_sync_tran_subscribed, has_unchecked_assembly_data, text_in_row_limit, large_value_types_out_of_row, is_tracked_by_cdc, lock_escalation, lock_escalation_desc, is_filetable, is_memory_optimized, durability, durability_desc, temporal_type, temporal_type_desc, history_table_id, is_remote_data_archive_enabled, is_external, history_retention_period, history_retention_period_unit, history_retention_period_unit_desc, is_node, is_edge) VALUES (N't_usr', 581577110, null, 1, 0, N'U ', N'USER_TABLE', N'2022-01-05 09:08:10.793', N'2022-01-05 09:19:05.670', 0, 0, 0, 0, null, 6, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, N'TABLE', 0, 0, 0, N'SCHEMA_AND_DATA', 0, N'NON_TEMPORAL_TABLE', null, 0, 0, null, null, null, 0, 0);
INSERT INTO sys.tables (name, object_id, principal_id, schema_id, parent_object_id, type, type_desc, create_date, modify_date, is_ms_shipped, is_published, is_schema_published, lob_data_space_id, filestream_data_space_id, max_column_id_used, lock_on_bulk_load, uses_ansi_nulls, is_replicated, has_replication_filter, is_merge_published, is_sync_tran_subscribed, has_unchecked_assembly_data, text_in_row_limit, large_value_types_out_of_row, is_tracked_by_cdc, lock_escalation, lock_escalation_desc, is_filetable, is_memory_optimized, durability, durability_desc, temporal_type, temporal_type_desc, history_table_id, is_remote_data_archive_enabled, is_external, history_retention_period, history_retention_period_unit, history_retention_period_unit_desc, is_node, is_edge) VALUES (N't_car', 901578250, null, 1, 0, N'U ', N'USER_TABLE', N'2022-01-05 09:17:12.853', N'2022-01-05 09:19:05.667', 0, 0, 0, 0, null, 11, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, N'TABLE', 0, 0, 0, N'SCHEMA_AND_DATA', 0, N'NON_TEMPORAL_TABLE', null, 0, 0, null, null, null, 0, 0);
INSERT INTO sys.tables (name, object_id, principal_id, schema_id, parent_object_id, type, type_desc, create_date, modify_date, is_ms_shipped, is_published, is_schema_published, lob_data_space_id, filestream_data_space_id, max_column_id_used, lock_on_bulk_load, uses_ansi_nulls, is_replicated, has_replication_filter, is_merge_published, is_sync_tran_subscribed, has_unchecked_assembly_data, text_in_row_limit, large_value_types_out_of_row, is_tracked_by_cdc, lock_escalation, lock_escalation_desc, is_filetable, is_memory_optimized, durability, durability_desc, temporal_type, temporal_type_desc, history_table_id, is_remote_data_archive_enabled, is_external, history_retention_period, history_retention_period_unit, history_retention_period_unit_desc, is_node, is_edge) VALUES (N't_rented', 949578421, null, 1, 0, N'U ', N'USER_TABLE', N'2022-01-05 09:19:05.667', N'2022-01-05 09:19:05.667', 0, 0, 0, 0, null, 7, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, N'TABLE', 0, 0, 0, N'SCHEMA_AND_DATA', 0, N'NON_TEMPORAL_TABLE', null, 0, 0, null, null, null, 0, 0);
INSERT INTO sys.tables (name, object_id, principal_id, schema_id, parent_object_id, type, type_desc, create_date, modify_date, is_ms_shipped, is_published, is_schema_published, lob_data_space_id, filestream_data_space_id, max_column_id_used, lock_on_bulk_load, uses_ansi_nulls, is_replicated, has_replication_filter, is_merge_published, is_sync_tran_subscribed, has_unchecked_assembly_data, text_in_row_limit, large_value_types_out_of_row, is_tracked_by_cdc, lock_escalation, lock_escalation_desc, is_filetable, is_memory_optimized, durability, durability_desc, temporal_type, temporal_type_desc, history_table_id, is_remote_data_archive_enabled, is_external, history_retention_period, history_retention_period_unit, history_retention_period_unit_desc, is_node, is_edge) VALUES (N't_maintain', 1013578649, null, 1, 0, N'U ', N'USER_TABLE', N'2022-01-05 09:19:58.530', N'2022-01-05 09:19:58.530', 0, 0, 0, 0, null, 7, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, N'TABLE', 0, 0, 0, N'SCHEMA_AND_DATA', 0, N'NON_TEMPORAL_TABLE', null, 0, 0, null, null, null, 0, 0);
INSERT INTO sys.tables (name, object_id, principal_id, schema_id, parent_object_id, type, type_desc, create_date, modify_date, is_ms_shipped, is_published, is_schema_published, lob_data_space_id, filestream_data_space_id, max_column_id_used, lock_on_bulk_load, uses_ansi_nulls, is_replicated, has_replication_filter, is_merge_published, is_sync_tran_subscribed, has_unchecked_assembly_data, text_in_row_limit, large_value_types_out_of_row, is_tracked_by_cdc, lock_escalation, lock_escalation_desc, is_filetable, is_memory_optimized, durability, durability_desc, temporal_type, temporal_type_desc, history_table_id, is_remote_data_archive_enabled, is_external, history_retention_period, history_retention_period_unit, history_retention_period_unit_desc, is_node, is_edge) VALUES (N't_admin', 1045578763, null, 1, 0, N'U ', N'USER_TABLE', N'2022-01-05 09:20:31.250', N'2022-01-05 09:20:31.250', 0, 0, 0, 0, null, 6, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, N'TABLE', 0, 0, 0, N'SCHEMA_AND_DATA', 0, N'NON_TEMPORAL_TABLE', null, 0, 0, null, null, null, 0, 0);
