create view sys.dm_tran_active_transactions as
-- missing source code
go

INSERT INTO sys.dm_tran_active_transactions (transaction_id, name, transaction_begin_time, transaction_type, transaction_uow, transaction_state, transaction_status, transaction_status2, dtc_state, dtc_status, dtc_isolation_level, filestream_transaction_id) VALUES (141, N'worktable', N'2022-01-05 08:55:47.960', 2, null, 2, 0, 0, 0, 0, 0, null);
INSERT INTO sys.dm_tran_active_transactions (transaction_id, name, transaction_begin_time, transaction_type, transaction_uow, transaction_state, transaction_status, transaction_status2, dtc_state, dtc_status, dtc_isolation_level, filestream_transaction_id) VALUES (144, N'worktable', N'2022-01-05 08:55:47.960', 2, null, 2, 0, 0, 0, 0, 0, null);
INSERT INTO sys.dm_tran_active_transactions (transaction_id, name, transaction_begin_time, transaction_type, transaction_uow, transaction_state, transaction_status, transaction_status2, dtc_state, dtc_status, dtc_isolation_level, filestream_transaction_id) VALUES (146, N'worktable', N'2022-01-05 08:55:47.960', 2, null, 2, 0, 0, 0, 0, 0, null);
INSERT INTO sys.dm_tran_active_transactions (transaction_id, name, transaction_begin_time, transaction_type, transaction_uow, transaction_state, transaction_status, transaction_status2, dtc_state, dtc_status, dtc_isolation_level, filestream_transaction_id) VALUES (148, N'worktable', N'2022-01-05 08:55:47.960', 2, null, 2, 0, 0, 0, 0, 0, null);
INSERT INTO sys.dm_tran_active_transactions (transaction_id, name, transaction_begin_time, transaction_type, transaction_uow, transaction_state, transaction_status, transaction_status2, dtc_state, dtc_status, dtc_isolation_level, filestream_transaction_id) VALUES (151, N'worktable', N'2022-01-05 08:55:47.960', 2, null, 2, 0, 0, 0, 0, 0, null);
INSERT INTO sys.dm_tran_active_transactions (transaction_id, name, transaction_begin_time, transaction_type, transaction_uow, transaction_state, transaction_status, transaction_status2, dtc_state, dtc_status, dtc_isolation_level, filestream_transaction_id) VALUES (154, N'worktable', N'2022-01-05 08:55:47.960', 2, null, 2, 0, 0, 0, 0, 0, null);
