create view sys.fulltext_languages as
-- missing source code
go

INSERT INTO sys.fulltext_languages (lcid, name) VALUES (5124, N'Chinese (Macao SAR)');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (4100, N'Chinese (Singapore)');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (3098, N'Serbian (Cyrillic)');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (3082, N'Spanish');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (3076, N'Chinese (Hong Kong SAR, PRC)');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (2074, N'Serbian (Latin)');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (2070, N'Portuguese');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (2057, N'British English');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (2052, N'Simplified Chinese');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1102, N'Marathi');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1100, N'Malayalam');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1099, N'Kannada');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1098, N'Telugu');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1097, N'Tamil');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1095, N'Gujarati');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1094, N'Punjabi');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1093, N'Bengali (India)');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1086, N'Malay - Malaysia');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1081, N'Hindi');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1066, N'Vietnamese');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1063, N'Lithuanian');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1062, N'Latvian');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1060, N'Slovenian');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1058, N'Ukrainian');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1057, N'Indonesian');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1056, N'Urdu');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1055, N'Turkish');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1054, N'Thai');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1053, N'Swedish');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1051, N'Slovak');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1050, N'Croatian');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1049, N'Russian');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1048, N'Romanian');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1046, N'Brazilian');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1045, N'Polish');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1044, N'Bokmål');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1043, N'Dutch');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1042, N'Korean');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1041, N'Japanese');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1040, N'Italian');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1039, N'Icelandic');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1037, N'Hebrew');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1036, N'French');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1033, N'English');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1032, N'Greek');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1031, N'German');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1030, N'Danish');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1029, N'Czech');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1028, N'Traditional Chinese');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1027, N'Catalan');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1026, N'Bulgarian');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (1025, N'Arabic');
INSERT INTO sys.fulltext_languages (lcid, name) VALUES (0, N'Neutral');
