create view INFORMATION_SCHEMA.SCHEMATA as
-- missing source code
go

INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES (N'db_rc', N'dbo', N'dbo', null, null, N'cp936');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES (N'db_rc', N'guest', N'guest', null, null, N'cp936');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES (N'db_rc', N'INFORMATION_SCHEMA', N'INFORMATION_SCHEMA', null, null, N'cp936');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES (N'db_rc', N'sys', N'sys', null, null, N'cp936');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES (N'db_rc', N'db_owner', N'db_owner', null, null, N'cp936');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES (N'db_rc', N'db_accessadmin', N'db_accessadmin', null, null, N'cp936');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES (N'db_rc', N'db_securityadmin', N'db_securityadmin', null, null, N'cp936');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES (N'db_rc', N'db_ddladmin', N'db_ddladmin', null, null, N'cp936');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES (N'db_rc', N'db_backupoperator', N'db_backupoperator', null, null, N'cp936');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES (N'db_rc', N'db_datareader', N'db_datareader', null, null, N'cp936');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES (N'db_rc', N'db_datawriter', N'db_datawriter', null, null, N'cp936');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES (N'db_rc', N'db_denydatareader', N'db_denydatareader', null, null, N'cp936');
INSERT INTO INFORMATION_SCHEMA.SCHEMATA (CATALOG_NAME, SCHEMA_NAME, SCHEMA_OWNER, DEFAULT_CHARACTER_SET_CATALOG, DEFAULT_CHARACTER_SET_SCHEMA, DEFAULT_CHARACTER_SET_NAME) VALUES (N'db_rc', N'db_denydatawriter', N'db_denydatawriter', null, null, N'cp936');
