create view sys.xml_schema_attributes as
-- missing source code
go

grant select on sys.xml_schema_attributes to [public]
go

INSERT INTO sys.xml_schema_attributes (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_default_fixed, must_be_qualified, default_value) VALUES (260, 1, 3, 1, N'lang', N'A', N'ATTRIBUTE', N'A', N'ATTRIBUTE', N'N', N'NONE', null, null, 0, 1, null);
INSERT INTO sys.xml_schema_attributes (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_default_fixed, must_be_qualified, default_value) VALUES (261, 1, 3, 1, N'base', N'A', N'ATTRIBUTE', N'A', N'ATTRIBUTE', N'N', N'NONE', null, null, 0, 1, null);
INSERT INTO sys.xml_schema_attributes (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_default_fixed, must_be_qualified, default_value) VALUES (262, 1, 3, 1, N'space', N'A', N'ATTRIBUTE', N'A', N'ATTRIBUTE', N'N', N'NONE', null, null, 0, 1, null);
INSERT INTO sys.xml_schema_attributes (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_default_fixed, must_be_qualified, default_value) VALUES (361, 1, 2, 1, N'sqlDbType', N'A', N'ATTRIBUTE', N'A', N'ATTRIBUTE', N'N', N'NONE', null, null, 0, 1, N'NVarChar');
INSERT INTO sys.xml_schema_attributes (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_default_fixed, must_be_qualified, default_value) VALUES (362, 1, 2, 1, N'clrTypeName', N'A', N'ATTRIBUTE', N'A', N'ATTRIBUTE', N'N', N'NONE', null, null, 0, 1, null);
INSERT INTO sys.xml_schema_attributes (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_default_fixed, must_be_qualified, default_value) VALUES (363, 1, 2, 1, N'maxLength', N'A', N'ATTRIBUTE', N'A', N'ATTRIBUTE', N'N', N'NONE', null, null, 0, 1, N'1');
INSERT INTO sys.xml_schema_attributes (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_default_fixed, must_be_qualified, default_value) VALUES (364, 1, 2, 1, N'localeId', N'A', N'ATTRIBUTE', N'A', N'ATTRIBUTE', N'N', N'NONE', null, null, 0, 1, N'-1');
INSERT INTO sys.xml_schema_attributes (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_default_fixed, must_be_qualified, default_value) VALUES (365, 1, 2, 1, N'sqlCompareOptions', N'A', N'ATTRIBUTE', N'A', N'ATTRIBUTE', N'N', N'NONE', null, null, 0, 1, N'Default');
INSERT INTO sys.xml_schema_attributes (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_default_fixed, must_be_qualified, default_value) VALUES (366, 1, 2, 1, N'sqlCollationVersion', N'A', N'ATTRIBUTE', N'A', N'ATTRIBUTE', N'N', N'NONE', null, null, 0, 1, N'0');
INSERT INTO sys.xml_schema_attributes (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_default_fixed, must_be_qualified, default_value) VALUES (367, 1, 2, 1, N'sqlSortId', N'A', N'ATTRIBUTE', N'A', N'ATTRIBUTE', N'N', N'NONE', null, null, 0, 1, N'0');
INSERT INTO sys.xml_schema_attributes (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_default_fixed, must_be_qualified, default_value) VALUES (368, 1, 2, 1, N'scale', N'A', N'ATTRIBUTE', N'A', N'ATTRIBUTE', N'N', N'NONE', null, null, 0, 1, N'0');
INSERT INTO sys.xml_schema_attributes (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_default_fixed, must_be_qualified, default_value) VALUES (369, 1, 2, 1, N'precision', N'A', N'ATTRIBUTE', N'A', N'ATTRIBUTE', N'N', N'NONE', null, null, 0, 1, N'18');
INSERT INTO sys.xml_schema_attributes (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_default_fixed, must_be_qualified, default_value) VALUES (370, 1, 2, 1, N'xmlSchemaCollection', N'A', N'ATTRIBUTE', N'A', N'ATTRIBUTE', N'N', N'NONE', null, null, 0, 1, null);
INSERT INTO sys.xml_schema_attributes (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_default_fixed, must_be_qualified, default_value) VALUES (371, 1, 2, 1, N'sqlTypeAlias', N'A', N'ATTRIBUTE', N'A', N'ATTRIBUTE', N'N', N'NONE', null, null, 0, 1, null);
INSERT INTO sys.xml_schema_attributes (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_default_fixed, must_be_qualified, default_value) VALUES (372, 1, 2, 1, N'base64Encoded', N'A', N'ATTRIBUTE', N'A', N'ATTRIBUTE', N'N', N'NONE', null, null, 0, 1, null);
INSERT INTO sys.xml_schema_attributes (xml_component_id, xml_collection_id, xml_namespace_id, is_qualified, name, symbol_space, symbol_space_desc, kind, kind_desc, derivation, derivation_desc, base_xml_component_id, scoping_xml_component_id, is_default_fixed, must_be_qualified, default_value) VALUES (373, 1, 2, 1, N'supplementaryCharacters', N'A', N'ATTRIBUTE', N'A', N'ATTRIBUTE', N'N', N'NONE', null, null, 0, 1, N'false');
