create view sys.sysconfigures as
-- missing source code
go

INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 101, N'Maximum recovery interval in minutes', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 102, N'Allow updates to system tables', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 103, N'Number of user connections allowed', 2);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 106, N'Number of locks for all users', 2);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 107, N'Number of open database objects', 2);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 109, N'Default fill factor percentage', 2);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 114, N'Disallow returning results from triggers', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (1, 115, N'Allow triggers to be invoked within triggers', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (1, 116, N'Allow recursion for server level triggers', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (1, 117, N'Allow remote access', 0);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (30, 124, N'default language', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 400, N'Allow cross db ownership chaining', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 503, N'Maximum worker threads', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (4096, 505, N'Network packet size', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 518, N'show advanced options', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 542, N'Create DTC transaction for remote procedures', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 544, N'c2 audit mode', 2);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (2052, 1126, N'default full-text language', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (2049, 1127, N'two digit year cutoff', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1505, N'Memory for index create sorts (kBytes)', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1517, N'Priority boost', 2);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (10, 1519, N'remote login timeout', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (600, 1520, N'remote query timeout', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (-1, 1531, N'cursor threshold', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1532, N'set working set size', 2);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1534, N'user options', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1535, N'affinity mask', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (65536, 1536, N'Maximum size of a text field in replication.', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1537, N'Tape retention period in days', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (5, 1538, N'cost threshold for parallelism', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1539, N'maximum degree of parallelism', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (1024, 1540, N'minimum memory per query (kBytes)', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (-1, 1541, N'maximum time to wait for query memory (s)', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1543, N'Minimum size of server memory (MB)', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (2147483647, 1544, N'Maximum size of server memory (MB)', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1545, N'Maximum estimated cost allowed by query governor', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1546, N'User mode scheduler uses lightweight pooling', 2);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1547, N'scan for startup stored procedures', 2);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1549, N'affinity64 mask', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1550, N'affinity I/O mask', 2);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1551, N'affinity64 I/O mask', 2);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1555, N'Transform noise words for full-text query', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1556, N'Use precomputed rank for full-text query', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (60, 1557, N'DB connection timeout for full-text protocol handler (s)', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1562, N'CLR user code execution enabled in the server', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (4, 1563, N'Maximum  crawl ranges allowed in full-text indexing', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1564, N'Number of reserved full-text notifications buffers', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (100, 1565, N'Max number of full-text notifications buffers', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1566, N'Number of reserved full-text crawl buffers', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (100, 1567, N'Max number of full-text crawl buffers', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (1, 1568, N'Enable or disable the default trace', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1569, N'Blocked process reporting threshold', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1570, N'Recovery policy for DTC transactions with unknown outcome', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (60, 1573, N'The timeout of the user instance after no connection is made on the server', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (1, 1575, N'Enable or disable creation of user instances', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1576, N'Dedicated Admin Connections are allowed from remote clients', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1580, N'Sets the FILESTREAM access level', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1581, N'When this option is set, plan cache size is further reduced for single-use adhoc OLTP workload.', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1582, N'Default hash bucket count for the access check result security cache', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1583, N'Default quota for the access check result security cache', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1584, N'Enable checksum of backups by default', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1585, N'Automatic soft-NUMA is enabled by default', 2);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1586, N'Allows execution of external scripts', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (1, 1587, N'CLR strict security enabled in the server', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1588, N'Type of enclave used for computations on encrypted columns', 0);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1591, N'ADR cleaner retry timeout.', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 1592, N'ADR Preallocation Factor.', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 16384, N'Enable or disable Agent XPs', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 16386, N'Enable or disable Database Mail XPs', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (1, 16387, N'Enable or disable SMO and DMO XPs', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 16388, N'Enable or disable Ole Automation Procedures', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 16390, N'Enable or disable command shell', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 16391, N'Enable or disable Ad Hoc Distributed Queries', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 16392, N'Enable or disable Replication XPs', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 16393, N'Enables contained databases and contained authentication', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 16394, N'Configure SQL Server to connect to external Hadoop or Microsoft Azure storage blob data sources through PolyBase', 0);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (1, 16395, N'Configure SQL Server to encrypt control and data channels when using PolyBase', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 16396, N'Allow the use of the REMOTE_DATA_ARCHIVE data access for databases', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 16397, N'Allow INSERT into a Hadoop external table', 1);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (1, 16398, N'Allow enumeration of filesystem', 3);
INSERT INTO sys.sysconfigures (value, config, comment, status) VALUES (0, 16399, N'Configure SQL Server to connect to external data sources through PolyBase', 1);
