create view sys.dm_tran_database_transactions as
-- missing source code
go

INSERT INTO sys.dm_tran_database_transactions (transaction_id, database_id, database_transaction_begin_time, database_transaction_type, database_transaction_state, database_transaction_status, database_transaction_status2, database_transaction_log_record_count, database_transaction_replicate_record_count, database_transaction_log_bytes_used, database_transaction_log_bytes_reserved, database_transaction_log_bytes_used_system, database_transaction_log_bytes_reserved_system, database_transaction_begin_lsn, database_transaction_last_lsn, database_transaction_most_recent_savepoint_lsn, database_transaction_commit_lsn, database_transaction_last_rollback_lsn, database_transaction_next_undo_lsn) VALUES (148, 2, null, 2, 3, 0, 256, 0, 0, 0, 0, 0, 0, null, null, null, null, null, null);
INSERT INTO sys.dm_tran_database_transactions (transaction_id, database_id, database_transaction_begin_time, database_transaction_type, database_transaction_state, database_transaction_status, database_transaction_status2, database_transaction_log_record_count, database_transaction_replicate_record_count, database_transaction_log_bytes_used, database_transaction_log_bytes_reserved, database_transaction_log_bytes_used_system, database_transaction_log_bytes_reserved_system, database_transaction_begin_lsn, database_transaction_last_lsn, database_transaction_most_recent_savepoint_lsn, database_transaction_commit_lsn, database_transaction_last_rollback_lsn, database_transaction_next_undo_lsn) VALUES (141, 2, null, 2, 3, 0, 256, 0, 0, 0, 0, 0, 0, null, null, null, null, null, null);
INSERT INTO sys.dm_tran_database_transactions (transaction_id, database_id, database_transaction_begin_time, database_transaction_type, database_transaction_state, database_transaction_status, database_transaction_status2, database_transaction_log_record_count, database_transaction_replicate_record_count, database_transaction_log_bytes_used, database_transaction_log_bytes_reserved, database_transaction_log_bytes_used_system, database_transaction_log_bytes_reserved_system, database_transaction_begin_lsn, database_transaction_last_lsn, database_transaction_most_recent_savepoint_lsn, database_transaction_commit_lsn, database_transaction_last_rollback_lsn, database_transaction_next_undo_lsn) VALUES (146, 2, null, 2, 3, 0, 256, 0, 0, 0, 0, 0, 0, null, null, null, null, null, null);
INSERT INTO sys.dm_tran_database_transactions (transaction_id, database_id, database_transaction_begin_time, database_transaction_type, database_transaction_state, database_transaction_status, database_transaction_status2, database_transaction_log_record_count, database_transaction_replicate_record_count, database_transaction_log_bytes_used, database_transaction_log_bytes_reserved, database_transaction_log_bytes_used_system, database_transaction_log_bytes_reserved_system, database_transaction_begin_lsn, database_transaction_last_lsn, database_transaction_most_recent_savepoint_lsn, database_transaction_commit_lsn, database_transaction_last_rollback_lsn, database_transaction_next_undo_lsn) VALUES (151, 2, null, 2, 3, 0, 256, 0, 0, 0, 0, 0, 0, null, null, null, null, null, null);
INSERT INTO sys.dm_tran_database_transactions (transaction_id, database_id, database_transaction_begin_time, database_transaction_type, database_transaction_state, database_transaction_status, database_transaction_status2, database_transaction_log_record_count, database_transaction_replicate_record_count, database_transaction_log_bytes_used, database_transaction_log_bytes_reserved, database_transaction_log_bytes_used_system, database_transaction_log_bytes_reserved_system, database_transaction_begin_lsn, database_transaction_last_lsn, database_transaction_most_recent_savepoint_lsn, database_transaction_commit_lsn, database_transaction_last_rollback_lsn, database_transaction_next_undo_lsn) VALUES (144, 2, null, 2, 3, 0, 256, 0, 0, 0, 0, 0, 0, null, null, null, null, null, null);
INSERT INTO sys.dm_tran_database_transactions (transaction_id, database_id, database_transaction_begin_time, database_transaction_type, database_transaction_state, database_transaction_status, database_transaction_status2, database_transaction_log_record_count, database_transaction_replicate_record_count, database_transaction_log_bytes_used, database_transaction_log_bytes_reserved, database_transaction_log_bytes_used_system, database_transaction_log_bytes_reserved_system, database_transaction_begin_lsn, database_transaction_last_lsn, database_transaction_most_recent_savepoint_lsn, database_transaction_commit_lsn, database_transaction_last_rollback_lsn, database_transaction_next_undo_lsn) VALUES (154, 2, null, 2, 3, 0, 256, 0, 0, 0, 0, 0, 0, null, null, null, null, null, null);
