create view sys.server_permissions as
-- missing source code
go

INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 1, 1, N'COSQ', N'CONNECT SQL', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 2, 1, N'VWDB', N'VIEW ANY DATABASE', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 101, 1, N'VWAD', N'VIEW ANY DEFINITION', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 102, 1, N'AUTH', N'AUTHENTICATE SERVER', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 102, 1, N'VWAD', N'VIEW ANY DEFINITION', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 102, 1, N'VWSS', N'VIEW SERVER STATE', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 103, 1, N'AUTH', N'AUTHENTICATE SERVER', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 105, 1, N'CL  ', N'CONTROL SERVER', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 105, 1, N'VWAD', N'VIEW ANY DEFINITION', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 106, 1, N'VWAD', N'VIEW ANY DEFINITION', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 256, 1, N'COSQ', N'CONNECT SQL', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 257, 1, N'COSQ', N'CONNECT SQL', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 257, 1, N'VWAD', N'VIEW ANY DEFINITION', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 257, 1, N'VWSS', N'VIEW SERVER STATE', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 258, 1, N'COSQ', N'CONNECT SQL', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 259, 1, N'COSQ', N'CONNECT SQL', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 260, 1, N'COSQ', N'CONNECT SQL', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 261, 1, N'COSQ', N'CONNECT SQL', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 262, 1, N'COSQ', N'CONNECT SQL', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 263, 1, N'COSQ', N'CONNECT SQL', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 264, 1, N'ALAG', N'ALTER ANY AVAILABILITY GROUP', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 264, 1, N'COSQ', N'CONNECT SQL', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 264, 1, N'VWSS', N'VIEW SERVER STATE', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 265, 1, N'AAES', N'ALTER ANY EVENT SESSION', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 265, 1, N'CADB', N'CONNECT ANY DATABASE', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 265, 1, N'COSQ', N'CONNECT SQL', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 265, 1, N'VWAD', N'VIEW ANY DEFINITION', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (100, N'SERVER', 0, 0, 265, 1, N'VWSS', N'VIEW SERVER STATE', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (105, N'ENDPOINT', 2, 0, 2, 1, N'CO  ', N'CONNECT', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (105, N'ENDPOINT', 3, 0, 2, 1, N'CO  ', N'CONNECT', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (105, N'ENDPOINT', 4, 0, 2, 1, N'CO  ', N'CONNECT', N'G', N'GRANT');
INSERT INTO sys.server_permissions (class, class_desc, major_id, minor_id, grantee_principal_id, grantor_principal_id, type, permission_name, state, state_desc) VALUES (105, N'ENDPOINT', 5, 0, 2, 1, N'CO  ', N'CONNECT', N'G', N'GRANT');
