create view sys.dm_xtp_system_memory_consumers as
-- missing source code
go

INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (29, 2, N'VARHEAP', N'Lookaside heap', null, 0, 0, 0, 8, 73, 8, 3096, 0x00000233D5160480);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (28, 4, N'PGPOOL', N'256K page pool', null, 0, 0, 0, 1, 1, 262144, 262144, 0x00000233D58800F1);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (27, 4, N'PGPOOL', N'4K page pool', null, 0, 0, 0, 1, 1, 4096, 4096, 0x00000233D58000F1);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (26, 2, N'VARHEAP', N'System heap', null, 458752, 388352, 2068, 8, 112, 1, 16384, 0x00000233D51603C0);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (25, 1, N'LOOKASIDE', N'Transaction list element', 24, 0, 0, 0, 14, 1, 24, 24, 0x00000233D51610B1);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (24, 1, N'LOOKASIDE', N'Delta tracker cursor', 23, 0, 0, 0, 14, 1, 64, 64, 0x00000233D5161061);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (23, 1, N'LOOKASIDE', N'Transaction delta tracker', 22, 0, 0, 0, 14, 1, 48, 48, 0x00000233D5161011);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (22, 1, N'LOOKASIDE', N'Creation Statement Id Map Entry', 21, 0, 0, 0, 14, 1, 32, 32, 0x00000233D5160FC1);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (21, 1, N'LOOKASIDE', N'Creation Statement Id Map', 20, 0, 0, 0, 14, 1, 72, 72, 0x00000233D5160F71);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (20, 1, N'LOOKASIDE', N'Log IO proxy', 19, 0, 0, 0, 14, 1, 248, 248, 0x00000233D5160F21);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (19, 1, N'LOOKASIDE', N'Log IO completion', 18, 0, 0, 0, 14, 1, 104, 104, 0x00000233D5160ED1);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (18, 1, N'LOOKASIDE', N'Sequence object insert row', 17, 0, 0, 0, 14, 1, 88, 88, 0x00000233D5160E81);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (17, 1, N'LOOKASIDE', N'Sequence object map entry', 16, 0, 0, 0, 14, 1, 32, 32, 0x00000233D5160E31);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (16, 1, N'LOOKASIDE', N'Sequence object values map', 15, 0, 0, 0, 14, 1, 192, 192, 0x00000233D5160DE1);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (15, 1, N'LOOKASIDE', N'Redo transaction map entry', 14, 0, 0, 0, 14, 1, 72, 72, 0x00000233D5160D91);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (14, 1, N'LOOKASIDE', N'Transaction recent rows', 13, 0, 0, 0, 14, 1, 720, 720, 0x00000233D5160D41);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (13, 1, N'LOOKASIDE', N'Heap cursor', 12, 0, 0, 0, 14, 1, 480, 480, 0x00000233D5160CF1);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (12, 1, N'LOOKASIDE', N'Range cursor', 11, 0, 0, 0, 14, 1, 848, 848, 0x00000233D5160CA1);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (11, 1, N'LOOKASIDE', N'Hash cursor', 10, 0, 0, 0, 14, 1, 328, 328, 0x00000233D5160C51);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (10, 1, N'LOOKASIDE', N'Transaction dependent ring buffer', 9, 0, 0, 0, 14, 1, 1560, 1560, 0x00000233D5160C01);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (9, 1, N'LOOKASIDE', N'Transaction save-point set entry', 8, 0, 0, 0, 14, 1, 112, 112, 0x00000233D5160BB1);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (8, 1, N'LOOKASIDE', N'Transaction FK validation sets', 7, 0, 0, 0, 14, 1, 96, 96, 0x00000233D5160B61);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (7, 1, N'LOOKASIDE', N'Transaction partially-inserted rows set', 6, 0, 0, 0, 14, 1, 536, 536, 0x00000233D5160B11);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (6, 1, N'LOOKASIDE', N'Transaction constraint set', 5, 0, 0, 0, 14, 1, 2584, 2584, 0x00000233D5160AC1);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (5, 1, N'LOOKASIDE', N'Transaction save-point set', 4, 0, 0, 0, 14, 1, 536, 536, 0x00000233D5160A71);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (4, 1, N'LOOKASIDE', N'Transaction write set', 3, 0, 0, 0, 14, 1, 1304, 1304, 0x00000233D5160A21);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (3, 1, N'LOOKASIDE', N'Transaction scan set', 2, 0, 0, 0, 14, 1, 2840, 2840, 0x00000233D51609D1);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (2, 1, N'LOOKASIDE', N'Transaction read set', 1, 0, 0, 0, 14, 1, 3096, 3096, 0x00000233D5160981);
INSERT INTO sys.dm_xtp_system_memory_consumers (memory_consumer_id, memory_consumer_type, memory_consumer_type_desc, memory_consumer_desc, lookaside_id, allocated_bytes, used_bytes, allocation_count, partition_count, sizeclass_count, min_sizeclass, max_sizeclass, memory_consumer_address) VALUES (1, 1, N'LOOKASIDE', N'Transaction', 0, 0, 0, 0, 14, 1, 1472, 1472, 0x00000233D5160931);
