create view sys.trace_events as
-- missing source code
go

INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (10, 11, N'RPC:Completed');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (11, 11, N'RPC:Starting');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (12, 13, N'SQL:BatchCompleted');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (13, 13, N'SQL:BatchStarting');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (14, 8, N'Audit Login');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (15, 8, N'Audit Logout');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (16, 3, N'Attention');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (17, 10, N'ExistingConnection');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (18, 8, N'Audit Server Starts And Stops');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (19, 12, N'DTCTransaction');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (20, 8, N'Audit Login Failed');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (21, 3, N'EventLog');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (22, 3, N'ErrorLog');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (23, 4, N'Lock:Released');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (24, 4, N'Lock:Acquired');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (25, 4, N'Lock:Deadlock');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (26, 4, N'Lock:Cancel');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (27, 4, N'Lock:Timeout');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (28, 6, N'Degree of Parallelism');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (33, 3, N'Exception');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (34, 11, N'SP:CacheMiss');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (35, 11, N'SP:CacheInsert');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (36, 11, N'SP:CacheRemove');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (37, 11, N'SP:Recompile');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (38, 11, N'SP:CacheHit');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (40, 13, N'SQL:StmtStarting');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (41, 13, N'SQL:StmtCompleted');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (42, 11, N'SP:Starting');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (43, 11, N'SP:Completed');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (44, 11, N'SP:StmtStarting');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (45, 11, N'SP:StmtCompleted');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (46, 5, N'Object:Created');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (47, 5, N'Object:Deleted');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (50, 12, N'SQLTransaction');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (51, 7, N'Scan:Started');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (52, 7, N'Scan:Stopped');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (53, 1, N'CursorOpen');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (54, 12, N'TransactionLog');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (55, 3, N'Hash Warning');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (58, 6, N'Auto Stats');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (59, 4, N'Lock:Deadlock Chain');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (60, 4, N'Lock:Escalation');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (61, 15, N'OLEDB Errors');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (67, 3, N'Execution Warnings');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (68, 6, N'Showplan Text (Unencoded)');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (69, 3, N'Sort Warnings');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (70, 1, N'CursorPrepare');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (71, 13, N'Prepare SQL');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (72, 13, N'Exec Prepared SQL');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (73, 13, N'Unprepare SQL');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (74, 1, N'CursorExecute');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (75, 1, N'CursorRecompile');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (76, 1, N'CursorImplicitConversion');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (77, 1, N'CursorUnprepare');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (78, 1, N'CursorClose');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (79, 3, N'Missing Column Statistics');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (80, 3, N'Missing Join Predicate');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (81, 9, N'Server Memory Change');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (82, 14, N'UserConfigurable:0');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (83, 14, N'UserConfigurable:1');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (84, 14, N'UserConfigurable:2');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (85, 14, N'UserConfigurable:3');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (86, 14, N'UserConfigurable:4');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (87, 14, N'UserConfigurable:5');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (88, 14, N'UserConfigurable:6');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (89, 14, N'UserConfigurable:7');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (90, 14, N'UserConfigurable:8');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (91, 14, N'UserConfigurable:9');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (92, 2, N'Data File Auto Grow');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (93, 2, N'Log File Auto Grow');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (94, 2, N'Data File Auto Shrink');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (95, 2, N'Log File Auto Shrink');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (96, 6, N'Showplan Text');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (97, 6, N'Showplan All');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (98, 6, N'Showplan Statistics Profile');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (100, 11, N'RPC Output Parameter');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (102, 8, N'Audit Database Scope GDR Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (103, 8, N'Audit Schema Object GDR Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (104, 8, N'Audit Addlogin Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (105, 8, N'Audit Login GDR Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (106, 8, N'Audit Login Change Property Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (107, 8, N'Audit Login Change Password Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (108, 8, N'Audit Add Login to Server Role Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (109, 8, N'Audit Add DB User Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (110, 8, N'Audit Add Member to DB Role Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (111, 8, N'Audit Add Role Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (112, 8, N'Audit App Role Change Password Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (113, 8, N'Audit Statement Permission Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (114, 8, N'Audit Schema Object Access Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (115, 8, N'Audit Backup/Restore Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (116, 8, N'Audit DBCC Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (117, 8, N'Audit Change Audit Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (118, 8, N'Audit Object Derived Permission Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (119, 15, N'OLEDB Call Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (120, 15, N'OLEDB QueryInterface Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (121, 15, N'OLEDB DataRead Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (122, 6, N'Showplan XML');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (123, 6, N'SQL:FullTextQuery');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (124, 16, N'Broker:Conversation');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (125, 18, N'Deprecation Announcement');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (126, 18, N'Deprecation Final Support');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (127, 3, N'Exchange Spill Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (128, 8, N'Audit Database Management Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (129, 8, N'Audit Database Object Management Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (130, 8, N'Audit Database Principal Management Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (131, 8, N'Audit Schema Object Management Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (132, 8, N'Audit Server Principal Impersonation Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (133, 8, N'Audit Database Principal Impersonation Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (134, 8, N'Audit Server Object Take Ownership Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (135, 8, N'Audit Database Object Take Ownership Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (136, 16, N'Broker:Conversation Group');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (137, 3, N'Blocked process report');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (138, 16, N'Broker:Connection');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (139, 16, N'Broker:Forwarded Message Sent');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (140, 16, N'Broker:Forwarded Message Dropped');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (141, 16, N'Broker:Message Classify');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (142, 16, N'Broker:Transmission');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (143, 16, N'Broker:Queue Disabled');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (144, 16, N'Broker:Mirrored Route State Changed');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (146, 6, N'Showplan XML Statistics Profile');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (148, 4, N'Deadlock graph');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (149, 16, N'Broker:Remote Message Acknowledgement');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (150, 9, N'Trace File Close');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (151, 2, N'Database Mirroring Connection');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (152, 8, N'Audit Change Database Owner');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (153, 8, N'Audit Schema Object Take Ownership Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (154, 8, N'Audit Database Mirroring Login');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (155, 17, N'FT:Crawl Started');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (156, 17, N'FT:Crawl Stopped');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (157, 17, N'FT:Crawl Aborted');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (158, 8, N'Audit Broker Conversation');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (159, 8, N'Audit Broker Login');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (160, 16, N'Broker:Message Undeliverable');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (161, 16, N'Broker:Corrupted Message');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (162, 3, N'User Error Message');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (163, 16, N'Broker:Activation');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (164, 5, N'Object:Altered');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (165, 6, N'Performance statistics');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (166, 13, N'SQL:StmtRecompile');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (167, 2, N'Database Mirroring State Change');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (168, 6, N'Showplan XML For Query Compile');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (169, 6, N'Showplan All For Query Compile');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (170, 8, N'Audit Server Scope GDR Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (171, 8, N'Audit Server Object GDR Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (172, 8, N'Audit Database Object GDR Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (173, 8, N'Audit Server Operation Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (175, 8, N'Audit Server Alter Trace Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (176, 8, N'Audit Server Object Management Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (177, 8, N'Audit Server Principal Management Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (178, 8, N'Audit Database Operation Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (180, 8, N'Audit Database Object Access Event');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (181, 12, N'TM: Begin Tran starting');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (182, 12, N'TM: Begin Tran completed');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (183, 12, N'TM: Promote Tran starting');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (184, 12, N'TM: Promote Tran completed');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (185, 12, N'TM: Commit Tran starting');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (186, 12, N'TM: Commit Tran completed');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (187, 12, N'TM: Rollback Tran starting');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (188, 12, N'TM: Rollback Tran completed');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (189, 4, N'Lock:Timeout (timeout > 0)');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (190, 19, N'Progress Report: Online Index Operation');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (191, 12, N'TM: Save Tran starting');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (192, 12, N'TM: Save Tran completed');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (193, 3, N'Background Job Error');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (194, 15, N'OLEDB Provider Information');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (195, 9, N'Mount Tape');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (196, 20, N'Assembly Load');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (198, 13, N'XQuery Static Type');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (199, 21, N'QN: Subscription');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (200, 21, N'QN: Parameter table');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (201, 21, N'QN: Template');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (202, 21, N'QN: Dynamics');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (212, 3, N'Bitmap Warning');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (213, 3, N'Database Suspect Data Page');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (214, 3, N'CPU threshold exceeded');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (215, 10, N'PreConnect:Starting');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (216, 10, N'PreConnect:Completed');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (217, 6, N'Plan Guide Successful');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (218, 6, N'Plan Guide Unsuccessful');
INSERT INTO sys.trace_events (trace_event_id, category_id, name) VALUES (235, 8, N'Audit Fulltext');
