create view sys.types as
-- missing source code
go

grant select on sys.types to [public]
go

INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'image', 34, 34, 4, null, 16, 0, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'text', 35, 35, 4, null, 16, 0, 0, N'Chinese_PRC_CI_AS', 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'uniqueidentifier', 36, 36, 4, null, 16, 0, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'date', 40, 40, 4, null, 3, 10, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'time', 41, 41, 4, null, 5, 16, 7, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'datetime2', 42, 42, 4, null, 8, 27, 7, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'datetimeoffset', 43, 43, 4, null, 10, 34, 7, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'tinyint', 48, 48, 4, null, 1, 3, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'smallint', 52, 52, 4, null, 2, 5, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'int', 56, 56, 4, null, 4, 10, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'smalldatetime', 58, 58, 4, null, 4, 16, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'real', 59, 59, 4, null, 4, 24, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'money', 60, 60, 4, null, 8, 19, 4, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'datetime', 61, 61, 4, null, 8, 23, 3, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'float', 62, 62, 4, null, 8, 53, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'sql_variant', 98, 98, 4, null, 8016, 0, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'ntext', 99, 99, 4, null, 16, 0, 0, N'Chinese_PRC_CI_AS', 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'bit', 104, 104, 4, null, 1, 1, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'decimal', 106, 106, 4, null, 17, 38, 38, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'numeric', 108, 108, 4, null, 17, 38, 38, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'smallmoney', 122, 122, 4, null, 4, 10, 4, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'bigint', 127, 127, 4, null, 8, 19, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'hierarchyid', 240, 128, 4, null, 892, 0, 0, null, 1, 0, 1, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'geometry', 240, 129, 4, null, -1, 0, 0, null, 1, 0, 1, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'geography', 240, 130, 4, null, -1, 0, 0, null, 1, 0, 1, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'varbinary', 165, 165, 4, null, 8000, 0, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'varchar', 167, 167, 4, null, 8000, 0, 0, N'Chinese_PRC_CI_AS', 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'binary', 173, 173, 4, null, 8000, 0, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'char', 175, 175, 4, null, 8000, 0, 0, N'Chinese_PRC_CI_AS', 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'timestamp', 189, 189, 4, null, 8, 0, 0, null, 0, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'nvarchar', 231, 231, 4, null, 8000, 0, 0, N'Chinese_PRC_CI_AS', 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'nchar', 239, 239, 4, null, 8000, 0, 0, N'Chinese_PRC_CI_AS', 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'xml', 241, 241, 4, null, -1, 0, 0, null, 1, 0, 0, 0, 0, 0);
INSERT INTO sys.types (name, system_type_id, user_type_id, schema_id, principal_id, max_length, precision, scale, collation_name, is_nullable, is_user_defined, is_assembly_type, default_object_id, rule_object_id, is_table_type) VALUES (N'sysname', 231, 256, 4, null, 256, 0, 0, N'Chinese_PRC_CI_AS', 0, 0, 0, 0, 0, 0);
