create view sys.dm_os_waiting_tasks as
-- missing source code
go

INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB0508C8, 12, 0, 2782, N'XE_DISPATCHER_WAIT', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB050CA8, 2, 0, 850, N'SLEEP_TASK', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB051088, 10, 0, 2042447, N'KSOURCE_WAKEUP', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB05ACA8, null, null, 2754, N'QDS_PERSIST_TASK_MAIN_LOOP_SLEEP', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB05B088, null, null, 2043067, N'XTP_PREEMPTIVE_TASK', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB05B848, 14, 0, 2042466, N'BROKER_TRANSMITTER', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB0628C8, null, null, 2043088, N'QDS_ASYNC_QUEUE', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB062CA8, 3, 0, 2043067, N'WAIT_XTP_HOST_WAIT', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233CC9208C8, 36, 0, 226, N'SLEEP_TASK', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB06ACA8, 21, 0, 223, N'CHECKPOINT_QUEUE', 0x000000AE949FE9F0, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB06B468, 22, 0, 1827949, N'BROKER_EVENTHANDLER', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB072CA8, 1, 0, 792, N'SLEEP_TASK', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB073088, 6, 0, 126, N'LAZYWRITER_SLEEP', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB07ACA8, 5, 0, 2043065, N'PVS_PREALLOCATE', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB07B468, 25, 0, 2042466, N'BROKER_TRANSMITTER', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB682CA8, 24, 0, 64, N'ONDEMAND_TASK_QUEUE', 0x000000AE94FFE7B0, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB683088, 23, 0, 2042661, N'FT_IFTSHC_MUTEX', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB683848, 26, 0, 761, N'SLEEP_TASK', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB68ACA8, 11, 0, 2565, N'XE_TIMER_EVENT', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB68B088, 9, 0, 4779, N'REQUEST_FOR_DEADLOCK_SEARCH', 0x000000AE941FE510, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB68B848, null, null, 46337, N'FT_IFTS_SCHEDULER_IDLE_WAIT', 0x0000000000000001, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB68BC28, 27, 0, 52, N'HADR_FILESTREAM_IOMGR_IOCOMPLETION', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233DB6BA4E8, 13, 0, 64, N'SLEEP_TASK', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233D52EA4E8, 4, 0, 100, N'DIRTY_PAGE_POLL', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233D52F24E8, 7, 0, 68, N'LOGMGR_QUEUE', 0x000000AE95BFC7B0, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233D52FA4E8, 8, 0, 84, N'LOGMGR_QUEUE', 0x000000AE961FC7C0, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233D5BEE4E8, null, null, 4901, N'CLR_AUTO_EVENT', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233D326A4E8, null, null, 4901, N'CLR_AUTO_EVENT', null, null, null, null, null);
INSERT INTO sys.dm_os_waiting_tasks (waiting_task_address, session_id, exec_context_id, wait_duration_ms, wait_type, resource_address, blocking_task_address, blocking_session_id, blocking_exec_context_id, resource_description) VALUES (0x00000233D3E684E8, 19, 0, 2755, N'SQLTRACE_INCREMENTAL_FLUSH_SLEEP', null, null, null, null, null);
