create view INFORMATION_SCHEMA.KEY_COLUMN_USAGE as
-- missing source code
go

INSERT INTO INFORMATION_SCHEMA.KEY_COLUMN_USAGE (CONSTRAINT_CATALOG, CONSTRAINT_SCHEMA, CONSTRAINT_NAME, TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION) VALUES (N'db_rc', N'dbo', N'PK__t_admin__3213E83F410C283D', N'db_rc', N'dbo', N't_admin', N'id', 1);
INSERT INTO INFORMATION_SCHEMA.KEY_COLUMN_USAGE (CONSTRAINT_CATALOG, CONSTRAINT_SCHEMA, CONSTRAINT_NAME, TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION) VALUES (N'db_rc', N'dbo', N'PK__t_car__3213E83F32068265', N'db_rc', N'dbo', N't_car', N'id', 1);
INSERT INTO INFORMATION_SCHEMA.KEY_COLUMN_USAGE (CONSTRAINT_CATALOG, CONSTRAINT_SCHEMA, CONSTRAINT_NAME, TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION) VALUES (N'db_rc', N'dbo', N'PK__t_mainta__3213E83FBF210321', N'db_rc', N'dbo', N't_maintain', N'id', 1);
INSERT INTO INFORMATION_SCHEMA.KEY_COLUMN_USAGE (CONSTRAINT_CATALOG, CONSTRAINT_SCHEMA, CONSTRAINT_NAME, TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION) VALUES (N'db_rc', N'dbo', N'PK__t_rented__3213E83FD2B202F6', N'db_rc', N'dbo', N't_rented', N'id', 1);
INSERT INTO INFORMATION_SCHEMA.KEY_COLUMN_USAGE (CONSTRAINT_CATALOG, CONSTRAINT_SCHEMA, CONSTRAINT_NAME, TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION) VALUES (N'db_rc', N'dbo', N'PK__t_usr__3213E83F67A1B7B9', N'db_rc', N'dbo', N't_usr', N'id', 1);
INSERT INTO INFORMATION_SCHEMA.KEY_COLUMN_USAGE (CONSTRAINT_CATALOG, CONSTRAINT_SCHEMA, CONSTRAINT_NAME, TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION) VALUES (N'db_rc', N'dbo', N't_rented_t_car_id_fk', N'db_rc', N'dbo', N't_rented', N'carID', 1);
INSERT INTO INFORMATION_SCHEMA.KEY_COLUMN_USAGE (CONSTRAINT_CATALOG, CONSTRAINT_SCHEMA, CONSTRAINT_NAME, TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION) VALUES (N'db_rc', N'dbo', N't_rented_t_user_id_fk', N'db_rc', N'dbo', N't_rented', N'usrID', 1);
