create view sys.dm_tran_persistent_version_store_stats as
-- missing source code
go

INSERT INTO sys.dm_tran_persistent_version_store_stats (database_id, pvs_filegroup_id, persistent_version_store_size_kb, online_index_version_store_size_kb, current_aborted_transaction_count, oldest_active_transaction_id, oldest_aborted_transaction_id, min_transaction_timestamp, online_index_min_transaction_timestamp, secondary_low_water_mark, offrow_version_cleaner_start_time, offrow_version_cleaner_end_time, aborted_version_cleaner_start_time, aborted_version_cleaner_end_time, pvs_off_row_page_skipped_low_water_mark, pvs_off_row_page_skipped_transaction_not_cleaned, pvs_off_row_page_skipped_oldest_active_xdesid, pvs_off_row_page_skipped_min_useful_xts, pvs_off_row_page_skipped_oldest_snapshot) VALUES (1, 1, 0, 0, 0, 0, 0, 25, 25, 0, null, null, null, null, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_tran_persistent_version_store_stats (database_id, pvs_filegroup_id, persistent_version_store_size_kb, online_index_version_store_size_kb, current_aborted_transaction_count, oldest_active_transaction_id, oldest_aborted_transaction_id, min_transaction_timestamp, online_index_min_transaction_timestamp, secondary_low_water_mark, offrow_version_cleaner_start_time, offrow_version_cleaner_end_time, aborted_version_cleaner_start_time, aborted_version_cleaner_end_time, pvs_off_row_page_skipped_low_water_mark, pvs_off_row_page_skipped_transaction_not_cleaned, pvs_off_row_page_skipped_oldest_active_xdesid, pvs_off_row_page_skipped_min_useful_xts, pvs_off_row_page_skipped_oldest_snapshot) VALUES (2, 1, 0, 0, 0, 0, 0, 25, 25, 0, null, null, null, null, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_tran_persistent_version_store_stats (database_id, pvs_filegroup_id, persistent_version_store_size_kb, online_index_version_store_size_kb, current_aborted_transaction_count, oldest_active_transaction_id, oldest_aborted_transaction_id, min_transaction_timestamp, online_index_min_transaction_timestamp, secondary_low_water_mark, offrow_version_cleaner_start_time, offrow_version_cleaner_end_time, aborted_version_cleaner_start_time, aborted_version_cleaner_end_time, pvs_off_row_page_skipped_low_water_mark, pvs_off_row_page_skipped_transaction_not_cleaned, pvs_off_row_page_skipped_oldest_active_xdesid, pvs_off_row_page_skipped_min_useful_xts, pvs_off_row_page_skipped_oldest_snapshot) VALUES (3, 1, 0, 0, 0, 0, 0, 25, 25, 0, null, null, null, null, 0, 0, 0, 0, 0);
INSERT INTO sys.dm_tran_persistent_version_store_stats (database_id, pvs_filegroup_id, persistent_version_store_size_kb, online_index_version_store_size_kb, current_aborted_transaction_count, oldest_active_transaction_id, oldest_aborted_transaction_id, min_transaction_timestamp, online_index_min_transaction_timestamp, secondary_low_water_mark, offrow_version_cleaner_start_time, offrow_version_cleaner_end_time, aborted_version_cleaner_start_time, aborted_version_cleaner_end_time, pvs_off_row_page_skipped_low_water_mark, pvs_off_row_page_skipped_transaction_not_cleaned, pvs_off_row_page_skipped_oldest_active_xdesid, pvs_off_row_page_skipped_min_useful_xts, pvs_off_row_page_skipped_oldest_snapshot) VALUES (4, 1, 0, 0, 0, 0, 0, 25, 25, 0, N'2022-01-05 09:29:55.2100000', N'2022-01-05 09:29:55.2100000', N'2022-01-05 08:56:47.5700000', N'2022-01-05 08:56:47.8133333', 0, 0, 0, 0, 0);
INSERT INTO sys.dm_tran_persistent_version_store_stats (database_id, pvs_filegroup_id, persistent_version_store_size_kb, online_index_version_store_size_kb, current_aborted_transaction_count, oldest_active_transaction_id, oldest_aborted_transaction_id, min_transaction_timestamp, online_index_min_transaction_timestamp, secondary_low_water_mark, offrow_version_cleaner_start_time, offrow_version_cleaner_end_time, aborted_version_cleaner_start_time, aborted_version_cleaner_end_time, pvs_off_row_page_skipped_low_water_mark, pvs_off_row_page_skipped_transaction_not_cleaned, pvs_off_row_page_skipped_oldest_active_xdesid, pvs_off_row_page_skipped_min_useful_xts, pvs_off_row_page_skipped_oldest_snapshot) VALUES (5, 1, 0, 0, 0, 0, 0, 25, 25, 0, N'2022-01-05 09:29:55.2100000', N'2022-01-05 09:29:55.2100000', N'2022-01-05 09:10:53.5066667', N'2022-01-05 09:10:53.5233333', 0, 0, 0, 0, 0);
INSERT INTO sys.dm_tran_persistent_version_store_stats (database_id, pvs_filegroup_id, persistent_version_store_size_kb, online_index_version_store_size_kb, current_aborted_transaction_count, oldest_active_transaction_id, oldest_aborted_transaction_id, min_transaction_timestamp, online_index_min_transaction_timestamp, secondary_low_water_mark, offrow_version_cleaner_start_time, offrow_version_cleaner_end_time, aborted_version_cleaner_start_time, aborted_version_cleaner_end_time, pvs_off_row_page_skipped_low_water_mark, pvs_off_row_page_skipped_transaction_not_cleaned, pvs_off_row_page_skipped_oldest_active_xdesid, pvs_off_row_page_skipped_min_useful_xts, pvs_off_row_page_skipped_oldest_snapshot) VALUES (32767, 1, 0, 0, 0, 0, 0, 25, 25, 0, null, null, null, null, 0, 0, 0, 0, 0);
